### PR TITLE
Solved multiple bugs in module info dialog

### LINKED ISSUE #128: Multiple bugs in module-dialog
There are multiple bugs present in the module info dialog:

* Info and Warning Popup stay open after closing and re-opening dialog (Expected behavior: closed).
* Config edit field stays in edit mode after closing and re-opening dialog (Expected behavior: view mod).
* Config edit does not work properly.

### PR DESCRIPTION
**Pull request by AnjaBruls**
This resolves #128 .

### CODE REVIEW

File: src/Stores/NodesStore.js [hunk 1]
```diff
@@ -397,7 +397,7 @@ class NodesStore extends BaseStore {
     }
 
     onSetModuleConf(nodeId, name, configuration, tag, cb) {
-        const query = `set_module_conf('${name}', ${configuration ? `'${configuration}'` : 'nil'});`;
+        const query = `set_module_conf('${name}', ${configuration ? `${configuration}` : 'nil'});`;
```
Comment (joente) [inline src/Stores/NodesStore.js:400]: It would be better to use query arguments instead of "building' the query, thus:

```
query = set_module_conf(name, configuration);
```
and as arguments:
```
{
  "name": name,
  "configuration: configuration
}
```

This way, it is also fine if configuration is `nil`, since that will be correctly packed.

**Review by joente — CHANGES_REQUESTED** [review]
Instead of query building, it would be an improvement to use query arguments instead.

**Review by joente — APPROVED** [review]

File: src/Stores/NodesStore.js (hunk 1 above)
Comment (AnjaBruls) [reply src/Stores/NodesStore.js:400]: This will be changed in a later release (~v0.4.4).
